### ISSUE TITLE
dcat:distribution without mandatory title

### ISSUE THREAD

**Issue by volkerjaenisch** [GovDataOfficial/DCAT-AP.de#1]
I do not know a single system where an Entity does not have a (unique) title property.

One may argue that each distribution has a dataset which can lend a title.

My point of view is that we have to collect incomplete data from the data providers. The more complete the data model the more pressure we can act on the data providers to deliver complete data.

**Comment by GKStGovData** [comment]
Vielen Dank für den Beitrag. Die angeregte Änderung wurde im Rahmen der Erstellung der DCAT-AP.de Version 1.0.2 als CR2018/48 behandelt und abgelehnt, da title im darunterliegenden Application Profile optional ist und eine Verschärfung auf nationaler Seite nicht im Interesse der Interoperabilität ist.

**Comment by akuckartz** [comment]
Die Begründung ist nicht nachvollziehbar.
