### ISSUE TITLE
Verwendung "Datenstruktur" und "Datensatz"

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#10]
Teilweise wird für den selben Gegenstand das Wort "Datenstruktur" oder "Datensatz" verwendet. Dies sollte beim nächsten Major-Release vereinheitlicht werden. Dabei ist zu entscheiden, ob "Datenstruktur" oder "Datensatz" verwendet wird.

**Comment by schiersner** [comment]
**"Datensatz" sollte es werden.**
"Datenstruktur" mag für Kolleginnen und Kollegen aus der Informatik zutreffender sein, doch unsere größte Zielgruppe hat mit Informatik wenig zu schaffen. Unsere Fachsprache schreckt da nur ab.

**Comment by akuckartz** [comment]
Datenstruktur != Datensatz. Das sind keine Synonyme.

**Comment by schiersner** [comment]
Das habe ich auch nicht behauptet. Vielleicht lesen Sie meine Begründung noch einmal? Und was ist denn Ihre Position zu der eigentlichen Frage?

**Comment by akuckartz** [comment]
@schiersner Mein Kommentar bezog sich auf den Anfangsbeitrag. Ich bin dafür, "Datenstruktur" und "Datensatz" abhängig davon zu verwenden, was jeweils gemeint ist. Technische Spezifikationen sollten präzise sein und Fachbegriffe entsprechend der relevanten Fachsprache verwenden. Bei Bedarf kann man Begriffe kurz in einem Glossar erläutern.

**Comment by GKStGovData** [comment]
Stimmt, wir haben das gleiche Ziel. Es geht um eine eindeutige Festlegung und Verwendung der richtigen Fachbegriffe. Deshalb wurde die missverständliche Überschrift dieses Issues nun abgeändert.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
