### ISSUE TITLE
Regionalschlüssel für Ämter

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#12]
Mit dem Regionalschlüssel (ARS) können auch Ämter (kommunale Verwaltung zwischen Landkreis und Gemeinde) adressiert werden. So hat das Amt Hüttener Berge den ARS 010585890. In der bisherigen Liste der Regionalschlüssel https://www.dcat-ap.de/def/politicalGeocoding/regionalKey/ taucht das Amt noch nicht auf. Es wäre schön, wenn die Liste entsprechend erweitert werden könnte.

**Comment by GKStGovData** [comment]
Danke für den Kommentar. Auf [https://www.dcat-ap.de/def/politicalGeocoding/regionalKey/](https://www.dcat-ap.de/def/politicalGeocoding/regionalKey/) haben wir nun wieder den aktuellen Regionalschlüssel. Der aktuelle ARS ist seit 29.02.2020 gültig und folgender Quelle entnommen: [https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:rs_2020-02-29#version](https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:rs_2020-02-29#version)

**Comment by jze** [comment]
In der verwendeten Quelle sind die Ämter u.ä. nicht enthalten. In dieser Datei sind sie mit drin:
https://www.xrepository.de/api/xrepository/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:gemeindeverband_2019-05-31:technischerBestandteilGenericode

**Comment by GKStGovData** [comment]
Hier ein ergänzender Link mit Infos zur Codeliste Gemeindeverbände bei xRepository: [https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:gemeindeverband](url)

**Comment by GKStGovData** [comment]
Issue wurde in #21 behandelt und wird daher geschlossen.
