### ISSUE TITLE
genauere Hinweise zu dcatde:plannedAvailability

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#15]
Die Beschreibung zu `dcatde:plannedAvailability` finde ich noch nicht aussagekräftig genug. Es handelt sich um die Eigenschaft einer `Distribution`. Damit kann also nicht die generelle Verfügbarkeit des Datensatzes selbst gemeint sein. Das sollte dann nochmal deutlich sagt werden.

Mir fallen folgende Deutungsmöglichkeiten ein:

- das Format (der Datensatz wird weiterhin als JSON-Datei angeboten)
- die Adresse `dcat:downloadURL` ändert sich nicht

Welche ist gemeint? Gibt es weitere Deutungsmöglichkeiten?

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#status-und-erwartete-verfugbarkeit) umgesetzt.
