### ISSUE TITLE
dcatde:plannedAvailability auch für Dataset

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#16]
`dcatde:plannedAvailability` sollte es auch für `Dataset` geben. Es könnte sein, dass ein Datensatz erst probehalber bereitgestellt wird, um zu sehen, ob er brauchbar ist. Ebenso könnte bereits absehbar sein, dass er mit anderen Datensätzen (zu landesweiten Datenbeständen) verbunden wird. 

Bei einem `Dataset` vom Typ `Colleciton` könnte es (ggf. in Kombination mit `dcat:granularity`) auch als Hinweis gesehen werden, ob die Datenerfassung fortgeführt wird.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
