### ISSUE TITLE
Mapping von ISO Metadaten auf DCAT-AP.de Verwendung von dct:modified vereinheitlichen  

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#18]
Aktuell werden für das GovData-Portal von unterschiedlichen Portalen identische Datensätze bereitgestellt, die per Mapping aus ISO-Metadaten die DCAT-AP.de Metadaten erzeugt haben. Damit diese Datensätze zuverlässig als Dublette erkannt werden, muss (neben dem Identifier) das Mapping auf dct:modified bei allen datenbereitstellenden Portalen standardisiert sein. Eine entsprechende Regelung sollte hierfür in das DCAT-AP.de
Konventionenhandbuch (https://www.dcat-ap.de/def/dcatde/1.0.2/implRules.pdf) aufgenommen werden.

**Comment by jze** [comment]
Einige Beispiele wären schön. Gibt es schon eine Idee, wie das Standard-Mapping aussehen könnte?

**Comment by GKStGovData** [comment]
Generell kommen nach unserem Kenntnisstand eignen sich insbesondere zwei Datumsangaben aus den ISO-Metadaten. 

1. Das „fachliche“ Aktualitätsdatum der Ressource (Daten oder Dienst) im Element date (XPath MD_Metadata/identificationInfo[1]/*/citation/CI_Citation/date/CI_Date/date), dieses wird üblicherweise nur nach Überarbeitung bzw. Aktualisierung der Daten selbst bzw. des Dienstes verändert. Die Handhabung bei Datenbeständen, für die eine kontinuierliche Fortführung erfolgt, ist dabei unterschiedlich und obliegt dem jeweiligen Metadatenerfasser.

2. Das „technische“ Aktualitätsdatum der Metadaten (Daten oder Dienst) im Element dateStamp (XPath MD_Metadata/dateStamp), das das ausschlaggebende Merkmal für Veränderungen in den Metadaten ist.

**Comment by GKStGovData** [comment]
Lösung: 
Im Minor-Release wird im Konventionenhandbuch für GovData das technische Aktualisierungsdatum aus den ISO-Metadaten verpflichtend für das Mapping auf dct:modified festgelegt.

Für das Major-Release wird erneut geprüft, ob die Notwendigkeit besteht, neue Attribute zur Abbildung einer fachlichen Aktualisierung einzuführen.
