### ISSUE TITLE
Liste der geopolitischen Verwaltungscodierung - Regierungsbezirke

### ISSUE THREAD

**Issue by open-nrw** [GovDataOfficial/DCAT-AP.de#19]
In der Liste der geopolitischen Verwaltungscodierung https://www.dcat-ap.de/def/politicalGeocoding/Level/ gibt es keinen Eintrag für die Regierungsbezirke. Es wäre schön, wenn die Liste entsprechend erweitert werden könnte.

**Comment by tfechner** [comment]
Es gibt Regierungsbezirke in 
* Baden-Württemberg 
* Bayern
* Hessen 
* Nordrhein-Westfalen

Die Struktur der AGS sieht die Untergliederung in Regierungsbezirke bereits vor, es müssten nur die Listen in DCAT-Ap.de erweitert werden.

1.–2. Stelle   = Kennzahl des Bundeslandes
3. Stelle      = Kennzahl des Regierungsbezirks; wenn nicht vorhanden: 0
4.–5. Stelle   = Kennzahl des Landkreises oder der kreisfreien Stadt
6.–9. Stelle   = Verbandsschlüssel
10.–12. Stelle = Gemeindekennzahl

**Comment by GKStGovData** [comment]
Danke für den Beitrag. Enthält die Liste "Bezirke bzw. Regierungsbezirke der deutschen Bundesländer nach dem Gemeindeverzeichnis des Statistischen Bundesamtes" die von Ihnen gewünschten Informationen? Hier der Link zur Liste: https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:bezirk#version

**Comment by open-nrw** [comment]
Für NRW ist die Liste vollständig und korrekt.

**Comment by GKStGovData** [comment]
Issue wurde in #21 behandelt und wird daher geschlossen.
