### ISSUE TITLE
No SKOSConcept for the catalog

### ISSUE THREAD

**Issue by volkerjaenisch** [GovDataOfficial/DCAT-AP.de#2]
DCAT_catalog refers to a SKOSConceptScheme but has no reference to a SKOSConcept itself.
The notation that the dcat_catalog as the "container" of the dcat_dataset bears the pointer to the SKOSConceptScheme  is a bit old fashion in the context of semantic web.
Usually a SKOSConcept has a Backreference skos:inScheme to its SKOSConceptScheme

```
<https://opendata.potsdam.de/id/theme/Bev%C3%B6lkerung> a skos:Concept ;
    dct:title "Bevölkerung" ;
    skos:inScheme <https://opendata.potsdam.de/concept-scheme/themes> ;
    skos:prefLabel "Bevölkerung" .

<https://opendata.potsdam.de/id/theme/Infrastruktur%2C%20Bauen%20und%20Wohnen> a skos:Concept ;
    dct:title "Infrastruktur, Bauen und Wohnen" ;
    skos:inScheme <https://opendata.potsdam.de/concept-scheme/themes> ;
    skos:prefLabel "Infrastruktur, Bauen und Wohnen" .

<https://opendata.potsdam.de/concept-scheme/themes> a skos:ConceptScheme ;
    dct:title "Themes" ;
    skos:prefLabel "A Set of data themes" ;
    skos:topConceptOf <https://opendata.potsdam.de/id/theme/Bev%C3%B6lkerung>,
        <https://opendata.potsdam.de/id/theme/Infrastruktur%2C%20Bauen%20und%20Wohnen> .
```
So the Catalogs reference to the ConceptScheme is useless.

But if a catalog gets a SKOSConcept pointer instead this helps a lot to tag the datasets if they are not tagged.

**Comment by GKStGovData** [comment]
Vielen Dank für den Beitrag. Die angeregte Änderung wurde im Rahmen der Erstellung der DCAT-AP.de Version 1.0.2 als CR2018/49 behandelt und abgelehnt, da DCAT-AP.de hier ISA DCAT-AP und W3C DCAT folgt.
