### ISSUE TITLE
dct:Format / IANA Liste / Publications Office

### ISSUE THREAD

**Issue by tfechner** [GovDataOfficial/DCAT-AP.de#20]
Wie soll mit "neuen" Formaten für Distributionen umgegangen werden, welche nicht in der IANA Liste enthalten sind bzw. welche nicht in der Liste des Publications Office der EU enthalten sind? Wird eine harmonisierte Liste mit Empfehlungen für DE angestrebt?
 
Anregung: Können diese Formate / Media Types zentral gesammelt werden und in die IANA / bzw. Publication Office gestellt werden? Einzelne neue Formate einreichen erscheint nicht zielführend zu sein.

Aktuell wird als Medientyp / Format oft einfach ein String im RDF angegeben, obwohl eine URI abgebildet werden müsste.

Beispiel "WMS" / "OGC WMS" müsste lauf Publication Office als 

WMS_SRVC | http://publications.europa.eu/resource/authority/file-type/WMS_SRVC

abgebildet werden.  Das scheint in der Nutzung nicht praktikabel zu sein, außerdem tut es aktuell kein Datenbereitsteller. "WMS-SRVC" wird umgangssprachlich / in Fachkreisen nicht genutzt, sondern "WMS" bzw. "OGC WMS".

**Comment by init-dcat-ap-de** [comment]
Ist diese Frage nicht durch Konvention 31 gelöst:
> Konv 31: Hat die Datei, die die Daten einer Distribution beinhaltet, einen in der MDR authority
file table geführten mediaType, so MUSS auf diesen mittels dct:format verwiesen
werden. Andernfalls MUSS via dcat:mediaType auf die IANA Liste verwiesen und
ein ggf. fehlender mediaType dort angelegt werden.

**Comment by GKStGovData** [comment]
Aufgrund der oben zitierten Konvention 31 gibt es hierzu aus unserer Sicht keinen Änderungsbedarf am Standard.
