### ISSUE TITLE
Welche Listen von IRIs werden für dcatde:politicalGeocodingURI benötigt

### ISSUE THREAD

**Issue by init-dcat-ap-de** [GovDataOfficial/DCAT-AP.de#21]
Um den verwaltungspolitischer Geobezugs als URI (mittels `dcatde:politicalGeocodingURI`) angeben zu können, werden derzeit (Spezifikation S. 29 bzw. S. 45) drei Listen zur Verfügung gestellt:
> Für die Referenzierung der Bundesländer sollen Schlüssel im Namensraum http://dcatap.de/def/politicalGeocoding/stateKey/, für die Angabe von Gemeinden und Kommunen soll der Regionalschlüssel im Namensraum http://dcatap.de/def/politicalGeocoding/regionalKey/ für die Angabe von Landkreisen der Kreisschlüssel aus dem Namensraum http://dcatap.de/def/politicalGeocoding/districtKey/ verwendet werden.

Diese scheinen nicht ausreichend und/oder die falschen zu sein. (Siehe #11, #12 und #19). 

Hier soll geschlossen diskutiert und dokumentiert werden, welche Listen DCAT-AP als URI zu verfügung stellen soll. (Am besten mit Angabe der Quelle.)

**Comment by jze** [comment]
- Gemeinden über AGS
- Gemeinden über Regionalschlüssel ✔
- Verwaltungsgemeinschaften (Amt, Samtgemeinde, Verbandsgemeinde) als Regionalschlüssel
- Kreise ✔
- Regierungsbezirke
- Bundesländer ✔

**Comment by GKStGovData** [comment]
Aufnahme der folgenden Listen zur Abdeckung des verwaltungspolitischen Geobezugs als Ergänzung zu den bereits bestehenden Listen:

1.  Der AGS als alternative Möglichkeit zur Referenzierung der Gemeinden 
Quelle der Liste: https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:ags 
Name der Liste: https://www.dcat-ap.de/def/politicalGeocoding/municipalityKey/

2. Die Liste der Gemeindeverbände
Quelle der Liste: https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:gemeindeverband 
Name der Liste: https://www.dcat-ap.de/def/politicalGeocoding/municipalAssociationKey/

3. Die Liste der Bezirke bzw. Regierungsbezirke
Quelle der Liste:
https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:bezirk 
Name der Liste https://www.dcat-ap.de/def/politicalGeocoding/governmentDistrictKey/

**Comment by akuckartz** [comment]
I get 404 errors for the first six URLs.

**Comment by GKStGovData** [comment]
@akuckartz thx!  We have updated the links to the lists. The value lists for DCAT-AP.de are currently still under construction and will be published with version 1.1.
