### ISSUE TITLE
Kapitel über bekannte Nutzungen von DCAT-AP.de / DCAT-AP aufnehmen

### ISSUE THREAD

**Issue by init-dcat-ap-de** [GovDataOfficial/DCAT-AP.de#22]
Es wird angeregt in der nächsten Version 
a) der Spezifikation oder
b) dynamischer in einem Blog-Beitrag oder als HTML-Seite auf dcat-ap.de 
ein Kapitel aufzunehmen, welches zeigt:
Wer nutzt neben GovData DCAT-AP.de nach?
Welche anderen deutschen Vorhaben erstellen ein eigenes Profil von DCAT-AP?
Welche horizontalen und vertikalen Erweiterung vom EU DCAT-AP gibt es aktuell?

Zweck: 
1. Überblick bekommen über die Nutzer der deutschen, EU und W3C Spezifikation im deutschsprachigen Raum.
2. Möglichkeit geben des Community-Building z.B. um gemeinsam benötigte Vokabulare abzustimmen
3. Verständnis über die Bedeutung von DCAT-AP.de schärfen ausserhalb des GovData Horizontes

Bisher bekannte Nutzer:

**DCAT-AP.de as-is Nutzung**

Bund:
1. GovData - das Datenportal für Deutschland:
 Beispiel DCAT-AP.de Datensatz:  https://www.govdata.de/ckan/dataset/grundschulbezirke.rdf
2. BMFSFJ Open Data Portal:  https://www.daten.bmfsfj.de/
    Beispiel DCAT-AP.de Datensatz: https://www.daten.bmfsfj.de/blob/127546/406af2dd4df95a224ee62538ea2f7c55/uvg-leistungsberechtige-im-quartal-data.rdf
3. BMWi Open Data Portal (coming soon):

**DCAT-AP: eigene vertikale und horizontale Profilierungen analog zu DCAT-AP ** 

Bund

4. Bundesanstalt für Straßenwesen (BASt) mit dem eigenen Profil "DCAT-AP.NAP" 
https://www.its-platform.eu/highlights/harmonised-metadata-national-access-points

Vertikale (Sektorale) Nutzung durch eigene Profile:
EU:
1. BRegDCAT-AP - Spezifikation: Access to Base Register - Spezifikation zur Vernetzung von Basisregistern in Europa - https://joinup.ec.europa.eu/sites/default/files/document/2020-05/SC380_D02.01_Final%20Specification%20of%20the%20BRegDCAT-AP_v1.02.docx 
2. GeoDCAT-AP: Spezifikation: https://joinup.ec.europa.eu/solution/geodcat-application-profile-data-portals-europe/distribution/geodcat-ap-101-docx
3. StatDCAT-AP: Spezifikation: https://joinup.ec.europa.eu/solution/statdcat-application-profile-data-portals-europe/distribution/statdcat-ap-v101-pdf

Horizontale (landesspezifische) Nutzung durch Länder:
EU Mitgliedstaaten und EFTA Länder:
8. Italien:https://www.dati.gov.it/sites/default/files/2020-02/linee-guida-cataloghi-dati-profilo-dcat-ap-it-2.pdf 
9. Norwegen: https://data.norge.no/specification/dcat-ap-no/
10. Schweden: https://diggsweden.github.io/DCAT-AP-SE/en/
11. Belgien: http://dcat.be/

**Comment by init-dcat-ap-de** [comment]
**Liste der Datenbereitsteller die DCAT-AP.de anliefern:**
1. [RegionalStatistik](https://www.regionalstatistik.de)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)
1. [asdasd](dsasdas)

**Comment by jze** [comment]
**DCAT-AP.de as-is Nutzung**

- [Transparenzportal Schleswig-Holstein](https://transparenz.schleswig-holstein.de/dataset), mit Katalog-Schnittstelle https://transparenz.schleswig-holstein.de/catalog.xml

**Comment by init-dcat-ap-de** [comment]
Weiteres EU-Profil:
Dänemark: https://github.com/digst/DCAT-AP-DK

**Comment by GKStGovData** [comment]
@init-dcat-ap-de Danke für den Beitrag. Alternativ zu der Liste der Länder könnten wir auch auf die Liste des W3Cs zu den DCAT-AP Profilen verweisen (und dort ggf. Änderungsanträge stellen): https://www.w3.org/TR/vocab-dcat-2/#profiles

**Comment by init-dcat-ap-de** [comment]
DCAT-AP-OP: https://op.europa.eu/de/web/eu-vocabularies/dcat-ap 
Schweiz: https://www.ech.ch/de/standards/39919 mit https://github.com/factsmission/dcat-ap-ch-shacl
JCR: https://ec-jrc.github.io/dcat-ap-jrc/
