### ISSUE TITLE
Konv 27 führt zu ungültigen Daten

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#23]
Die Konvention 27 im [DCAT-AP.de Konventionenhandbuch 1.0.2](https://www.dcat-ap.de/def/dcatde/1.0.2/implRules.pdf) besagt:

> Bei Serialisierung in RDF/XML MUSS der dct:identifier einer Datenstruktur in das rdf:about Feld übernommen werden.

Laut [DCAT-AP.de Spezifikation 1.0.2](https://www.dcat-ap.de/def/dcatde/1.0.2/spec/specification.pdf) (Seite 26) ist `dct:identifier` aber ein Literal, kann also jeden beliebigen Wert annehmen. Die [Produktionsregel für rdf:about im RDF Standard](https://www.w3.org/TR/rdf-syntax-grammar/#aboutAttr) besagt aber, dass es eine URI-Referenz sein muss. Durch das Kopieren würde man also syntaktisch falsche RDF-Dokumente erzeugen, wenn `dct:identifier` keinen URI enthält. Dies ist bei ¾ der Datensätze bei GovData der Fall.

**Comment by jze** [comment]
Bei der Konvention 28 ist es das gleiche Problem für JSON-LD. Die müsse also auch gestrichen werden.

**Comment by GKStGovData** [comment]
@jze Danke für die Hinweise. Die Streichung der Konventionen 27 und 28 werden wir bei der Erstellung der nächsten DCAT-AP.de Version diskutieren.

**Comment by akuckartz** [comment]
Soweit es sich um Fehler handelt sollten sie zeitnah behoben werden.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konvention-27) umgesetzt.
