### ISSUE TITLE
Verwendung von dct:license

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#24]
In der [Spezifikation 1.0.2](https://www.dcat-ap.de/def/dcatde/1.0.2/spec/specification.pdf) fehlt auf Seite 41 die Nutzung von `dct:license` für die Klasse `dcat:Catalogue`, wie auf Seite 21 beschrieben.

**Comment by GKStGovData** [comment]
Danke für den Hinweis @jze Die Spezifikation wurde entsprechend aktualisiert.
