### ISSUE TITLE
dct:license auch für dcat:Dataset

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#25]
Auf für dcat:Dataset sollte es möglich sein, eine Lizenz anzugeben. Es müsste - bis auf wenige Ausnahmen von nicht-maschinenlesbaren Distributionen - sogar ausreichen, wenn man die Angabe zur Lizenz nur am Dataset unterbringt.

**Comment by GKStGovData** [comment]
@jze Danke für den Hinweis. Das Thema sollten wir bei dem nächsten Major-Release diskutieren.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
