### ISSUE TITLE
Dateiendung für URI-Konzept auf https://www.dcat-ap.de/def/ fehlt beim Speichern

### ISSUE THREAD

**Issue by ChristianHaider** [GovDataOfficial/DCAT-AP.de#26]
Der letzte Link auf der Seite https://www.dcat-ap.de/def/ unter "Dokumente und Artefakte" ist [URI-Konzept (PDF)](https://www.dcat-ap.de/def/uriConcept/1.0) , welcher beim Download eine Datei mit dem Namen "1.0" erzeugt.
Hier sollte zumindest die Endung ".pdf" dabeisein. Ein besserer Name wäre wünschenswert.

**Comment by akuckartz** [comment]
Die PDF Datei wird ausgeliefert. Insofern ist nichts "kaputt". Die angeregte Extension ".pdf" ist jedoch sinnvoll.

**Comment by GKStGovData** [comment]
Vielen Dank für den Hinweis @ChristianHaider . Die Webseite www.dcat-ap.de wurde entsprechend aktualisiert.
