### ISSUE TITLE
Alternative zu dct:source

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#27]
Laut Konvention 21 soll die Eigenschaft `dct:source` nicht verwendet werden. Daher bin ich auf der Suche nach einer Alternative, um folgenden Sachverhalt darzustellen: Dataset A und Dataset B wurden (mit Expertenwissen) zusammengerechnet und daraus ist Dataset C entstanden. Bei Dataset C würde ich nun gerne Verweise auf die beiden Quell-Datasets angeben.

Ohne Konvetion 21 hätte ich das (stark vereinfacht) folgendermaßen gelöst:

```
A a dcat:Dataset .
B a dcat:Dataset .
C a dcat:Dataset
    dct:source :A ;
    dct:source :B .
```

Gibt es bereits eine Alternative oder müssen wir uns eine neue Lösung ausdenken?

**Comment by init-dcat-ap-de** [comment]
Guten Tag,
die Konvention wurde erstellt, da dct:source zu unspezifisch ist, um im Kontext des GovData-Portals einheitlich ausgewertet zu werden. 
Im Rahmen der Open World im Semantic Web steht Ihnen `dct:source` natürlich weiterhin zur Verfügung, es wird für die Darstellung im Portal GovData nur nicht ausgewertet werden. 

DCAT 2 empfiehlt für Ihren Use-Case die Verwendung der Provenance-Ontologie, genauer gesagt
> **`prov:wasDerivedFrom`** supports a more specific relationship to an input or predecessor dataset compared with dct:source, which is not necessarily a previous dataset. - https://www.w3.org/TR/vocab-dcat-2/#examples-dataset-provenance 

Dieser Empfehlung schließen wir uns an.
