### ISSUE TITLE
Musterdatenkatalog in DCAT-AP.de

### ISSUE THREAD

**Issue by mariosorg** [GovDataOfficial/DCAT-AP.de#28]
Gemeinsam mit GovData haben die Bertelsmann Stiftung und weitere Partner den [Musterdatenkatalog](https://musterdatenkatalog.de) entwickelt. Die für Kommunen entwickelten über 300 Musterdatensätze könnten in DCAT-AP.de aufgenommen werden, damit diese Grundlagenarbeit am MDK auch langfristig strukturell in der Open-Data-Landschaft verankert wird. Ein zusätzliches Feld in DCAT-AP.de könnte über Referenzen befüllt werden, mit URIs für jeden einzelnen Musterdatensatz aus dem Musterdatenkatalog.

**Comment by GKStGovData** [comment]
@mariosorg danke für den Beitrag, wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren.

**Comment by init-dcat-ap-de** [comment]
Vorschlag: Ein Dataset verweist mittels [dct:references](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/references/) auf das Dataset, das Teil des Musterdatenkatalogs ist.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#verweis-auf-referenzobjekte) umgesetzt.
