### ISSUE TITLE
Dublicity of SKOS and Keywords

### ISSUE THREAD

**Issue by volkerjaenisch** [GovDataOfficial/DCAT-AP.de#3]
Why are there SKOSConcepts as well as Keywords?
From the perspective of the Semantic web they are equivalent.
So why making a difference? 
Keywords are local and therefore not interoperable. SKOS is designed for interoperability. So why not use SKOS  solely?

Volker

**Comment by akuckartz** [comment]
@volkerjaenisch In case you are not aware of them, please note that these projects are related:

For the next generation of DCAT (worldwide): https://github.com/w3c/dxwg
For DCAT-AP (Europe): https://github.com/SEMICeu/DCAT-AP

**Comment by volkerjaenisch** [comment]
Thank you Andreas for this valuable hint!

I will reflect this information in our bbopen repository. 
https://github.com/BB-Open .

Our primary target is to deliver robust controlled vocabularies for
DCAT-AP.de 1.0. This is the standard we are programming for with PKAN
https://github.com/BB-Open/pkan.dcatapde

We will participate in the discussion of 1.1 as well.

Cheers,

Volker

**Comment by ChrisWittig** [comment]
Hallo Herr Jaenisch, 

vielen Dank für Ihren Kommentar. 
Wie sie Kapitel 2 der Spezifikation entnehmen können, werden für DCAT-AP.de die durch DCAT-AP geforderten Vokabulare nachgenutzt. Darüber hinaus sind alle weiteren nicht in anderen Standards definierten Wertelisten im Konventionenhandbuch (http://www.dcat-ap.de/def/dcatde/1_0/implRules.pdf) und auf der Bereitstellungsseite http://www.dcat-ap.de/def/ versioniert aufgeführt.
Die Liste der Datenbereitsteller und der Lizenzen werden außerhalb des Releasezyklus gepflegt und ebenfalls über die DCAT-AP.de Veröffentlichungsplattform von Nutzern des Standardentwurfes nachgenutzt.
Die Spezifikation ist in dieser Form von der Fachgruppe beschlossen und beim IT-Planungsrat zum Beschluss als Austauschstandard für Verwaltungsdaten vorgelegt.

Die Bereitstellung der DCAT-AP.de Codelisten erfolgt via Content Negotiation nach W3C Empfehlungen (Best Practice Recipes for Publishing RDF Vocabularies: https://www.w3.org/TR/swbp-vocab-pub/ )  und wird in der Version 1.0.1.  (CR 2018/001, https://github.com/GovDataOfficial/DCAT-AP.de/blob/master/Change-Requests-f%C3%BCr-Release-1.0.1.pdf  )  in einer überarbeiteten RDF-Struktur resultieren. Diese Art der Bereitstellung von Wertelisten als  „SKOS-AP-EU“ Profil http://publications.europa.eu/mdr/authority/index.html) entspricht aktuellen Verfahren der Bereitstellung von Codelisten für das Europäischen Open Data Portal.

Bei der Weiterentwicklung von DCAT-AP.de freuen wir uns über Ihre Beiträge für die Version 1.1. Für die Weiterentwicklung wurde ein Verfahren beschlossen, bei dem die Einbindung der Öffentlichkeit von zentraler Bedeutung ist. Hierzu wird in Kürze mehr bekanntgegeben. Wie bereits angemerkt, ist eine dezentrale Diskussion über die Weiterentwicklung von DCAT-AP.de, wie von Ihnen in Ihrem Github-Repository vorgeschlagen,  bisher noch nicht vorgesehen und sollte mit der Fachgruppe abgestimmt werden. Nur so kann gewährleistet werden, dass die Weiterentwicklung von DCAT-AP.de zielführend am fachlichen Bedarf entlang unter Berücksichtigung bestehender Betriebsstrukturen umgesetzt werden kann. 

Christian Wittig 
(Geschäfts- und Koordinierungsstelle GovData)
