### ISSUE TITLE
dct:format und dcat:mediaType

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#30]
Wir benötigen eine klare Aussage, wie, in welcher Property und auf welche Art (Literal oder Resource) das Format einer Distribution angegeben werden soll. Offenbar ist das bisher nicht deutlich genug. 

Bislang verwenden inn Deutschland nur 35% eine Resource der Form:

```xml
<dct:format rdf:resource="http://publications.europa.eu/resource/authority/file-type/CSV"/>

```

In Schweden hingegen wird das Format einer Distribution so angegeben:

```xml
<dcterms:format>application/rdf+xml</dcterms:format>
```

Diese Form findet man in Deutschland praktisch gar nicht.

Die Property `dcat:mediaType` wird deutlich weniger verwendet (nur 14% der Distributionen). Etwa die Hälfte davon verwendet Resourcen der Form

```xml
<dcat:mediaType rdf:resource="https://www.iana.org/assignments/media-types/text/csv"/>
```

**Comment by GKStGovData** [comment]
Danke für den Hinweis @jze . Bei diesem Thema müsste auch die Formulierung der Konvention 31 diskutiert werden: 

> Konv 31: Hat die Datei, die die Daten einer Distribution beinhaltet, einen in der MDR authority file table17
geführten mediaType, so MUSS auf diesen mittels dct:format verwiesen werden. Andernfalls
MUSS via dcat:mediaType auf die IANA Liste18 verwiesen und ein ggf. fehlender mediaType
dort angelegt werden 

Quelle: https://www.dcat-ap.de/def/dcatde/1.1/implRules.pdf S. 22

**Comment by akuckartz** [comment]
Siehe auch https://github.com/SEMICeu/DCAT-AP/issues/173

**Comment by init-dcat-ap-de** [comment]
Mit [Konvention 31](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konvention-31) genau festgelegt.
