### ISSUE TITLE
Genauere Angaben zur Syntax von CSV-Dateien

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#31]
CSV-Dateien machen (vermutlich noch für lange Zeit) einen großen Teil der Distributionen aus. Die maschinelle Verarbeitung wird durch die vielfältigen Möglichkeiten des Formats erschwert. Oft finden sich Hinweise auf Zeichensatz, Trennzeichen etc. nur in der Beschreibung. 

In der Distribution sollten Informationen angegeben werden, mit denen man einen CSV-Datei automatisch einlesen kann:

- Zeichensatz
- Feldtrenner
- Zeichenketten-Trenner
- Dezimaltrennzeichen
- Zeilen-End-Zeichen

**Comment by GKStGovData** [comment]
@jze danke für den Beitrag. Wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren.

**Comment by jze** [comment]
Seieh auch #32
