### ISSUE TITLE
weitere Themen für Datasets

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#33]
Mit Hilfe der 13 von der EU definierten Themen lassen sich Datensätze nur grob (und oftmals unbetriedigend) gruppieren. Bei der Arbeit am Musterdatenkatalog ist eine Sammlung von 60 Themen entstanden:

- Abfallwirtschaft
- Bau
- Behörden
- Bevölkerung
- Bibliotheken
- Bildungsträger
- Bürgerbeteiligung
- Bürgerservice
- Energiewirtschaft
- Externe Infrastruktur
- Feuerwehr
- Freizeit
- Friedhöfe
- Fuhrpark
- Geschichte
- Gesundheitseinrichtungen
- Gewässer
- Grünflächen
- Haushalt
- Hochschulen
- Individualverkehr
- Infrastruktur
- Jugend
- Justiz
- Kindertageseinrichtungen
- Kultur
- Liegenschaften
- Museen
- Musikschulen
- Open Data
- Personal
- Politische Vertretung
- Radverkehr
- Raumordnung
- Rettungsdienst
- Schulen
- Senioren
- Sicherheit
- Soziale Hilfen
- Sport
- Sport- und Spielstätten
- Stadtarchiv
- Stadtmarketing
- Stadtplan
- Stadtwerke
- Steuern und Abgaben
- Theater
- Tiefbau
- Tourismus
- Umweltschutz
- Vereine, Verbände
- Volkshochschulen
- Wahlen
- Website
- Wetter
- Wirtschaft
- Wohnen
- Zivil- und Katastrophenschutz
- ÖPNV
- Öffentliche Wirtschaft
- Öffentlichkeitsarbeit

Auch in anderen Ländern scheint es ähnliche standardisierte Listen zu geben.

DCAT-AP.de könnte eine zusätzliche Liste mit URIs für Themen enthalten, mit denen man Datensätze genauer gruppieren kann.

**Comment by GKStGovData** [comment]
@jze danke für den Beitrag. Wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren.

**Comment by jze** [comment]
Eine weitere Möglichkeit zur Definition von Themen könnten die Aufgaben von Ministerien sein. Auch wenn die Themen in den einzelnen Bundesländern unterschiedlich auf die Ministerien verteilt sind, dürften doch (fast) alle Themen irgendwo auftauchen:

- Arbeit
- Außen
- Bau
- Bildung
- Digitalisierung
- Energie(wende)
- Ernährung
- Entwicklung
- Europa 
- Familie
- Frauen
- Finanzen
- Gesundheit
- Gleichstellung
- Heimat
- Inneres
- Integration  
- Jugend
- Justiz
- Kultur
- Landwirtschaft
- ländliche Räume
- Natur
- Senioren
- Soziales
- Staatskanzlei
- Technologie
- Tourismus
- Umwelt
- Verbraucherschutz
- Verkehr
- Verteidigung
- Wirtschaft
- Wissenschaft

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#angaben-zu-kategorien) umgesetzt.
