### ISSUE TITLE
Mehrere contributorIDs um Verlauf nachzuzeichnen

### ISSUE THREAD

**Issue by benjaminaaron** [GovDataOfficial/DCAT-AP.de#36]
Das kam mal in einem Call auf, ich weiß nicht mehr in welchem: die Möglichkeit Links zum gleichen Datensatz in anderen Portalen anzugeben. Zum einem im Sinne eines Verlaufs vertikal entlang der "Hochreichungslinie" (z.b. auf dem Weg vom kommunalen Portal zum europäischen Portal), als auch horizontal: Portale wo man sonst noch weiß das genau dieser Datensatz auch liegt. Hierfür wäre allerdings wohl die Konstruktion von geordneten als auch ungeordneten Listen nötig.
Auch mitzudenken wäre ggf. eine Variante der `contributorID` (`harvesterID`, `providerID`, `sourcePortalID`...?) die es Portalen erlaubt, von ihrer Seite aus einen Datensatz zu taggen - unabhängig davon was angeliefert kommt.
#40 würde auch Listen benötigen.

**Comment by GKStGovData** [comment]
@benjaminaaron danke für den Beitrag. Wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren.

**Comment by init-dcat-ap-de** [comment]
Mehrere contributerIDs sind bereits möglich, die Reihenfolge kann implizit aus den angegebenen Portalen abgeleitet werden.
Sofern kein weiterer Bedarf beschrieben wird, halten wir das für ausreichend.
