### ISSUE TITLE
Geodaten: Änderungen und Erhebungsmethoden

### ISSUE THREAD

**Issue by benjaminaaron** [GovDataOfficial/DCAT-AP.de#37]
@sebastian-meier meinte, es wäre wichtig bei Geodaten die Möglichkeit zu haben, Änderungen (change reports) zu vorigen Versionen zu tracken (z.B. "im Vergleich zum Vorjahr hat es folgende Veränderung in den Grunddaten gegeben") als auch die (Änderungen der) Erhebungsmethoden mit anzugeben.

**Comment by GKStGovData** [comment]
@benjaminaaron danke für den Beitrag. Wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren. Änderungen in den Erhebungsmethoden oder den Grunddaten könnten u.U. auch für andere Metadaten (bspw. bei Statistikdaten) interessant sein.

**Comment by GKStGovData** [comment]
@benjaminaaron und @sebastian-meier bei [DCAT-AP V 1.1 ](https://www.dcat-ap.de/def/dcatde/1.1/spec/specification.pdf) gibt es in der Klasse dcat:Dataset bereits Versionserläuterung (adms:versionNote): 

> Diese Eigenschaft enthält eine Beschreibung der Unterschiede zwischen dieser und den vorbestehenden Versionen der Datenstruktur.

Trifft das den genannten Bedarf?

**Comment by sebastian-meier** [comment]
Das trifft auf jeden Fall den Bedarf (zumindest von meiner Seite).  Dann wäre das übliche Problem nur das dieses Feld auch ausgefüllt werden müsste :)

Darüber hinaus wäre es interessant was dort hineingeschrieben werden sollte und auf welche Art und Weise. Hier wäre sicherlich ein Leitfaden für die Datenkoordinator*innen sehr hilfreich. Da Veränderungen ja sowohl methodisch (Erhebungsmethode) als auch strukturell (Erhebungsgebiet erweitert um Gebiet X, Gebiete Y und Z zusammengelegt, Veränderung der Kohortengrößen, etc.) beschrieben werden müssten.

**Comment by GKStGovData** [comment]
@sebastian-meier Danke für die schnelle Antwort. Wir können bei der Weiterentwicklung diskutieren, ob wir die Nutzung des Feldes (z.B. durch die Bearbeitung der Verbindlichkeit) zusätzlich fördern.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#angaben-zur-versionierung) umgesetzt.
