### ISSUE TITLE
Bei RDF Daten: Ontologien mit angeben

### ISSUE THREAD

**Issue by benjaminaaron** [GovDataOfficial/DCAT-AP.de#38]
Wenn es sich um Linked Data (RDF) handelt, sollte es die Möglichkeit geben eventuell verwendete Ontologien anzugeben.

**Comment by GKStGovData** [comment]
@benjaminaaron danke für den Beitrag. Wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren.

**Comment by init-dcat-ap-de** [comment]
Sollte über dct:conformsTo bereits möglich sein.
