### ISSUE TITLE
Attribut "temporalGranularity" (Muster-Vorschlag für Version 1.1)

### ISSUE THREAD

**Issue by init-dcat-ap-de** [GovDataOfficial/DCAT-AP.de#4]
**Bedarf**: Die zeitliche Auflösung (temporalGranularity) von Daten innerhalb eines Datensatzes soll als Metadatum zu einem Datensatz angegeben werden können. Dies ist z.B. ein relevantes Kriterium bei wissenschaftlichen Daten, die z.B. wöchentliche Messwerte enthalten.

**Lösungsvorschlag:** Aufnehmen eines neuen Attributs "temporalGranularity" auf Datensatzebene. Der Wertebereich hierfür sollte durch eine Codeliste mit Werten (stündlich, täglich, wöchentlich, monatlich, jährlich, etc.) festgelegt werden.

Martin Herzog
Mail: martin.herzog@init.de
Tel.: +49 30 97006 754

**Comment by akuckartz** [comment]
See also https://github.com/SEMICeu/DCAT-AP/issues/38

**Comment by GKStGovData** [comment]
Thank you for your suggestions. We will check them and take them into consideration in our review for DCAT-AP.de version 1.1.

**Comment by GKStGovData** [comment]
Vielen Dank für den Beitrag. Die angeregte Änderung wurde als CR2017/27 behandelt und in der DCAT-AP.de Version 1.0.2 umgesetzt. (Quelle: [https://github.com/GovDataOfficial/DCAT-AP.de/blob/master/CR-Dokumentation_1.0.2.xlsx]).
