### ISSUE TITLE
Für Visualisierungen positionieren

### ISSUE THREAD

**Issue by benjaminaaron** [GovDataOfficial/DCAT-AP.de#41]
Wer seine Daten gerne in (halb-)automatisch generierten Visualisierungen wiederfinden möchte, könnte die Möglichkeit bekommen bspw. Spalten als geeignete Hauptachsen zu markieren. Das [Visualisierungstool](https://visualize.admin.ch/) des [Linked-Data Dienst](https://lindas.admin.ch/) des Schweizer Bundesarchivs setzt auf [Data Cubes](https://www.w3.org/TR/vocab-data-cube/) um Dimensionen zu beschreiben.

**Comment by GKStGovData** [comment]
@benjaminaaron danke für den Beitrag. Wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren.

**Comment by init-dcat-ap-de** [comment]
Erscheint für die Meta-Daten nicht so relevant, sondern eher für die Inhaltsdaten.
Bei Bedarf kann das Data Cube Vokabular zusammen mit DCAT-AP.de genutzt werden.
