### ISSUE TITLE
Als machine-readable markieren

### ISSUE THREAD

**Issue by benjaminaaron** [GovDataOfficial/DCAT-AP.de#42]
Flags für _not-proprietary_, _machine-readable_, _is-an-API_ und ggf. weitere um alles mögliche zu markieren was es Crawlern/Scripts/Queries leichter macht, durch automatisch lesbare Inhalte zu gehen. @tori-d hat die Idee zu diesem Vorschlag in einem Gespräch geliefert.

**Comment by jze** [comment]
Im Sinne von Linked Open Data halte ich eine Markierung an der *Distribution* nicht für günstig, da es Eigenschaften des Formats sind. Das EDP hat sogar schon Properties `isMachineReadable` und `isNonProprietary`, die für Formate verwendet werden.

**Comment by GKStGovData** [comment]
@benjaminaaron und @jze danke für den Beiträge. Wir werden die Vorschläge im Rahmen der Weiterentwicklung des Standards diskutieren. Hier finden Sie Wertelisten des EDPs zu [`edp:isMachineReadable` ](https://gitlab.com/european-data-portal/edp-vocabularies/-/blob/master/edp-machine-readable-format.rdf) und `[edp:isNonProprietary](https://gitlab.com/european-data-portal/edp-vocabularies/-/blob/master/edp-non-proprietary-format.rdf)` Thematisch sollte das Issue gemeinsam mit #30 behandelt werden.

**Comment by init-dcat-ap-de** [comment]
Kein Handlungsbedarf für DCAT-AP.de.
Die EDP Listen ergänzen das empfohlene Vokabular um diese Information.
