### ISSUE TITLE
Ein Feld für was der Datensatz nicht beinhaltet

### ISSUE THREAD

**Issue by benjaminaaron** [GovDataOfficial/DCAT-AP.de#43]
Vielleicht könnte ein Feld Sinn machen wo der Datenbereitsteller eine Chance hat zu beschreiben was dieser Datensatz _nicht_ ist oder _nicht_ beinhaltet. Um bspw. bei bestimmten Daten üblichen Missverständnissen entgegenzuwirken oder Transparenz zu schaffen hinsichtlich was hier noch fehlt wenn man einen gründlichen Vollständigkeitsanspruch anlegt.

**Comment by jze** [comment]
Könntest du dafür ein Beispiel geben? Ich bin mir nicht sicher, ob ich die Idee verstanden habe.

**Comment by benjaminaaron** [comment]
Gerne: angenommen der Datensatz heißt "Busfahrplan Berlin Prenzlauer Berg" beinhaltet aber _nicht_ die Nachtbuslininen. Das könnte ein Fall für so ein Feld sein. Weil der Titel es weder eindeutig beinhaltet noch ausschließt das Nachtbuslinien mit dabei sind und Leute ggf. mit unterschiedlichen Erwartungen hinsichtlich Nachtbuslininen-dabei-oder-nicht den Datensatz öffnen.
Quasi wie ein "Verwirrungsauffangbecken": alles wo schon mal jemand den Datensatz aufgemacht hat und etwas anderes als erwartet vorgefunden hat könnte hier angegeben werden.

**Comment by akuckartz** [comment]
Solche Informationen können hilfreich sein. Aber ist es wirklich zielführend, wenn diese in einem _separaten_ Attribut enthalten sind?

**Comment by GKStGovData** [comment]
Eine Lösung könnte auch sein: Eine Empfehlung dazu entsprechende Informationen z.B. zu Erhebungsmethoden oder Lücken in der Datenquelle im Beschreibungstext (dct:description)  zu erfassen. Solche Empfehlungen finden sich auch in Leitfäden wie dem [NQDM](https://cdn0.scrvt.com/fokus/e472f1bf447f370f/32c99a36d8b3/NQDM_Leitfaden-f-r-qualitativ-hochwertige-Daten-und-Metadaten_2019.pdf) S. 48-49.  Zusätzlich könnten die Beschreibung der Beispieldateien einen solchen Hinweis enthalten.
