### ISSUE TITLE
Klare Aussagen zu Distribution

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#44]
Für DCAT-AP.de 2 wünsche ich mir eine klare Aussage, wann man mehrere *Distribution* für ein *Dataset* verwenden darf und wann nicht. Das European Data Portal macht es deutlich:

> If a dataset contains more than one distribution, all distributions are identical in content, they differ only in the representation of the data. For example, a dataset can have two distributions, one offering the data as PDF and the other offering the identical data as machine-readable RDF/XML.

https://www.europeandataportal.eu/mqa/methodology?locale=en

Auch beim W3C finden sich in der DCAT-Spzifikation solche Formulierungen:

> Examples of distributions include a CSV file, a netCDF file, a JSON document, or a data-cube, files made accessible according to different profiles, such as XML or JSON schemas or ShEx or SHACL expressions.

> As a counter-example, budget data for different years would usually be modelled as different datasets, each with their own distributions, since all distributions of one dataset should broadly contain the same data. 

https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution

**Comment by GKStGovData** [comment]
@jze danke für den Beitrag, wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren. Dabei sollten wir neben Spezifikation und Konventionenhandbuch auch den ["Leitfaden zur Berücksichtigung von Dokumenten im Metadatenkatalog von„GovData – das Datenportal für Deutschland“](https://www.govdata.de/documents/10156/18448/2020-07-29-Dokumente+im+GovData+Portal_Leitfaden_nach_Fachgruppensitzung.pdf/8c8be2ca-bd07-4f26-acb5-72a90d24a120) berücksichtigen. Hier wird es gestattet, auch zusätzliche Hinweise zur Nutzung der Distributionen in weiteren "erklärenden" Distributionen anzuhängen.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konventionen-zur-dcat-distribution) umgesetzt.
