### ISSUE TITLE
Hinweis zu Shape-Dateien

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#45]
Zumindest im Konventionenhandbuch sollte ein Hinweis enthalten sein, wie mit ESRI-Shape-Dateien umgegangen werden soll. Das dürfte im Bereich der Geo-Vektordaten das am häufigsten verwendete Dateiformat sein. In der Regel wird eine ZIP-Datei zum Download angeboten, die eine ganze Reihe von unterschiedlichen Dateien (shp, shx, dbf, prj) enthält. 

Im Konventionenhandbuch 1.0.2 stand unter Konvention 31 noch, dass man in dem Fall das Format  `http://publications.europa.eu/resource/authority/file-type/ZIP` verwenden soll. Im Konventionenhandbuch 1.1 ist diese Formulierung weggefallen. Für Nutzer*innen ist es aber nicht hilfreich, hier nur `ZIP` zu finden. Es sollte sofort erkennbar sein, dass es sich um eine Shape-Datei handelt.

**Comment by GKStGovData** [comment]
@jze danke für den Beitrag, wir werden den Vorschlag im Rahmen der Weiterentwicklung des Standards diskutieren. Die Erläuterungen zu Konvention 31 im [Konventionenhandbuch 1.1](https://www.dcat-ap.de/def/dcatde/1.1/implRules.pdf) besagen u.a.: 

> Im Falle eines Zip-Pakets muss hingegen
dcat:mediaType auf „https://www.iana.org/assignments/media-types/application/csv+zip20
“ verweisen.
Wäre nach der IANA-Liste noch keine geeignete Bezeichnung verfügbar gewesen, hätte sie bei IANA
registriert werden müssen (http://www.iana.org/form/media-types).
> 

Entspricht die Kennzeichnung (ggf. mit Nachregistrierung) bei dcat:mediaType  den Anforderungen?

**Comment by jze** [comment]
Die Kennzeichnung mit `mediaType` https://www.iana.org/assignments/media-types/application/csv+zip funktioniert aber nur, wenn ich in der ZIP-Datei **ausschließlich** CSV-Dateien befinden. Das ist bei den ESRI-Shape-Dateien aber nicht der Fall.

**Comment by init-dcat-ap-de** [comment]
Guten Tag,
bei ESRI-Shape Dateien reicht es, mit `dct:format` auf `<http://publications.europa.eu/resource/authority/file-type/SHP>` zu verweisen.

Siehe: https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konvention-31 und https://op.europa.eu/en/web/eu-vocabularies/concept/-/resource?uri=http://publications.europa.eu/resource/authority/file-type/SHP

**Comment by init-dcat-ap-de** [comment]
Spricht etwas dagegen, solche Distributionen wie folgt auszuzeichnen:

```
_:distr dct:format <http://publications.europa.eu/resource/authority/file-type/SHP> .
```

Man könnte noch als `dcat:compressFormat` angeben, dass es gezippt ist, aber das ist ja bereits durch [SHP](https://op.europa.eu/en/web/eu-vocabularies/concept/-/resource?uri=http://publications.europa.eu/resource/authority/file-type/SHP)vorgegeben.
Betroffene Konvention: https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konvention-31

**Comment by jze** [comment]
Als http://publications.europa.eu/resource/authority/file-type/SHP kennzeichne ich mittlerweile auch alle ESRI-Shape Dateien. Letztlich sind ja auch andere Dateiformate (z.B. [ODS](http://publications.europa.eu/resource/authority/file-type/ODS)) eigentlich nur ZIP-Dateien mit anderer Dateiendung. Möglicherweise gab es Anfang 2021 den file-type `SHP` noch nicht in der Liste.
