### ISSUE TITLE
Kennzeichnung für Markdown in dct:description

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#46]
Manche Portale verwenden in dct:description Markdown zur übersichtlicheren Darstellung umfangreicher Beschreibungen. Es wäre schön, wenn man markieren könnte, dass Markdown enthalten ist.

**Comment by GKStGovData** [comment]
@jze danke für den Beitrag. Wir werden den Vorschlag bei der Weiterentwicklung von DCAT-AP.de diskutieren. Dabei sollten wir berücksichtigen, wie viele Portale Markdown im Beschreibungstext korrekt darstellen können.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#formatierung-von-beschreibungen-dct-description) umgesetzt.
