### ISSUE TITLE
Konvention 1 dcat:contactPoint Pflicht "vcard:fn Name" streichen 

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#47]
Im [Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/1.1/implRules.pdf) Besagt die Konvention 1 zu dcat:contactPoint:

> Kontaktinformationen MÜSSEN mit Namen sowie Telefon und/oder Email unter Nutzung des
vcard Vokabulars hinterlegt werden.

Für die Kontaktaufnahme sind aber v.a. E-Mail-Adresse oder Telefonnummer wichtig. Daher sollte bei dcat:contactPoint die Verwendung von  vcard:hasEmail (E-Mailadresse) oder vcard:hasTelephone (Telefonnummer) verpflichtend sein und die Pflicht für vcard:fn (Name) entfallen.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konvention-01) umgesetzt.
