### ISSUE TITLE
Konv 12 u. Konv 13 dcatde:contributorID - Formulierung klarstellen und Beispiel ändern

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#48]
Die Konventionen 12 und 13 im [Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/1.1/implRules.pdf) beschreiben die Verwendung von dcatde:contributorID. Folgende zusätzliche Erläuterungen könnte noch mehr Klarheit für die Verwendung bringen: 

> Für die Quellportale, der an GovData anliefernden Portale, können wiederum eigene dcatde:contributorID URIs mit eigener Aufbauvorschrift  vergeben werden z.B. http://open.nrw/def/contributors/OpenDataKöln   

Ergänzend sollten die auf S. 14 beispielhaft aufgelisteten dcatde:contributorIDs entsprechend geändert werden z.B.:

> dcatde:contributorID <http://dcat-ap.de/def/contributors/openNRW>
dcatde:contributorID <http://open.nrw/def/contributors/OpenDataKöln>

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konvention-12) umgesetzt.
