### ISSUE TITLE
Open License (ISA Open Metadata License)

### ISSUE THREAD

**Issue by Ludee** [GovDataOfficial/DCAT-AP.de#5]
At the moment, this repository is lacking an (open) license.
The DCAT-AP is licensed under [ISA Open Metadata Licence v1.1](https://github.com/SEMICeu/DCAT-AP#licence).

Since this is a relatively new license, it is not yet registered in the [SPDX](https://spdx.org/licenses/) or the [Open Definition](https://opendefinition.org/licenses/).
In order to be accepted by a large community, it should be approved as "free/open". 
Here is a link how to apply for the [License Approval Process](https://opendefinition.org/licenses/process/) of the open definition.

**Comment by robbiemorrison** [comment]
Just to support the comment above. And to note that the SPDX project does not approve open software licenses, the [Open Source Initiative](https://opensource.org/) (OSI) does that instead. But in this case, seeking Open Definition approval would be a better [approach](https://opendefinition.org/licenses/process/). In addition, if you have legal advice on how this license interoperates with other common permissive licenses, including the Creative Commons family, then making that information public be very useful. HTH, Robbie.

**Comment by GKStGovData** [comment]
Thank you for your suggestions. We will check them and take them into consideration in our review for DCAT-AP.de version 1.1.

**Comment by robbiemorrison** [comment]
Thanks. Just to be clear. Once you have sought and gained open license approval from the Open Definition project, you should then talk to the SPDX project and register a license identifier. I guess that would be something like `ISA-OML-1.1` or `ISA-Open-Metadata-1.1`. Machine scannable license identifiers are becoming increasingly important with the development and deployment of automated license compliance tooling. And perhaps in the future, database management systems will also become metadata aware?

**Comment by akuckartz** [comment]
@robbiemorrison It is important to use URLs to identify licenses. That eliminates or reduces the requirement for registers. See also https://www.dcat-ap.de/def/licenses/

**Comment by GKStGovData** [comment]
https://github.com/SEMICeu/DCAT-AP/issues/63 
As DCAT-AP 2.0 solved this Issue by going under cc-by 4.0 we will follow them when upgrading on DCAT-AP.de 2.0.
