### ISSUE TITLE
Abgrenzung "plannedAvailability" und "adms:status" deutlich machen

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#50]
Aus dem Feedback von Datenbereitstellenden wurde deutlich, dass die Unterscheidung von "dcatde:plannedAvailability" und "adms:status" häufig schwer fällt.

Durch ein Beispiel im [Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/1.1/implRules.pdf) könnte hier Klarheit geschaffen werden. 

Bei diesem CR sollte auch die Übernahme der Eigenschaft dcatap:availability aus [DCAT-AP 2.0.1](https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.0.1/DCAT_AP_2.0.1.pdf) diskutiert werden

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#status-und-erwartete-verfugbarkeit) umgesetzt.
