### ISSUE TITLE
Koordinatenreferenzsystem in Konvention 4

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#51]
In Konvention 4 soll es vermutlich *Koordinatenreferenzsystem* statt *Koordinatensystem* heißen.

Das Beispiel auf Seite 8 sollte vereinfacht werden, da laut [GeoSPARQL Standard](https://portal.ogc.org/files/?artifact_id=47664) Req 11 bei WGS84 die URI nicht benötigt wird.

```rdf
:Resource locn:geometry "Point(-0.001475 51.477811)"^^gsp:wktLiteral .
```

Mit URI kann z.B. PostGIS den WKT nicht verarbeiten.

**Comment by GKStGovData** [comment]
@jze danke für den Beitrag. Wir werden den Vorschlag bei der Weiterentwicklung von DCAT-AP.de diskutieren.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von DCAT-AP.de 2.0 [im Konventionenhandbuch](https://www.dcat-ap.de/def/dcatde/2.0/implRules/#konvention-04) umgesetzt.
