### ISSUE TITLE
Einführung von dcat:DataService

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#53]
DCAT2 und DCAT-AP 2.0 führen die Klasse dcat:DataService ein: https://www.w3.org/TR/vocab-dcat-2/#Class:Data_Service
 
**Neue Klasse dcat:DataService**
-	dcat:endpointURL              – Range: rdfs:Resource      – Pflicht – 1..n
-	dct:title                           – Range: rdfs:Literal          – Pflicht – 1..n
-	dcat:servesDataset            – Range: dcat:Dataset        – Empfohlen – 0..n
-	dcat:endpointDescription     – Range: rdfs:Resource      – Empfohlen – 0..n
-	dct:descrpiption                – Range: rdfs:Literal          – Optional – 0..n 
-	dct:license                       – Range: dct: LicenseDocument  – Optional – 0..n 
-	dct:accessRights               – Range: dct:RightsStatement    – Optional – 0..n
 
**Neue Eigenschaft für dcat:Catalog**
-	dcat:service – Range: dcat:DataService – Optional 0..n
 
**Neue Eigenschaft für dcat:Distribution**
-	dcat:accessService – Range: dcat:DataService – Optional 0..n

DCAT2 und DCAT-AP 2.0 lassen viel Spielraum, wie ein DataService mit dcat:Catalog, dcat:Dataset und dcat:Distribution in Verbindung stehen.
 
**Für das Konventionenhandbuch** sollte festgelegt werden, wie diese Angaben erwartetet werden, damit sie vom GovData-Datenportal (sowie auch weiteren Portalen) korrekt dargestellt werden können.

Eine Idee wäre, den dcat:DataService als Option anzusehen, wie die Daten einer Distribution abgerufen werden können. Die Kette wäre demnach: 
-	Ein Catalog hat Datasets. 
-	Ein Dataset hat Distributionen. 
-	Eine Distribution nutzt einen DataService.
 
Weitere Konventionen wären:
-	Eine Distribution, die einen über einen DataService verfügt, SOLLTE über KEINE dcat:downloadURL verfügen.
-	Eine Distribution, die über einen DataService verfügt, MUSS als dcat:accessURL die dcat:endpointURL des DataService angeben.

**Comment by GKStGovData** [comment]
Ergänzend noch die Darstellung der Klasse dcat:DataService in PlantUML-Notation:

class "dcat:DataService" <<optional>> {

    <<mandatory>> dcat:endpointURL ~> rdfs:Resource [1..*]
    <<mandatory>> dct:title ~> rdfs:Literal [1..*]

    <<recommended>> dcat:endpointDescription ~> rdfs:Resource [*]

    <<optional>> dct:description ~> rdfs:Literal [*]
    <<optional>> dct:license ~> dct:LicenseDocument [*]
    <<optional>> dct:accessRights ~> dct:RightsStatement [*]
}

"dcat:DataService"  --> "*" "dcat:Dataset" : <<recommended>> NEU: dcat:servesDataset
"dcat:Catalog"      --> "*" "dcat:DataService" : <<optional>> NEU: dcat:service
"dcat:Distribution" --> "*" "dcat:DataService" : <<optional>> NEU: dcat:accessService 

![dcatDataService](https://user-images.githubusercontent.com/40267626/107938542-d7fdcc80-6f85-11eb-8b0e-bd46e66c300a.png)

**Comment by GKStGovData** [comment]
Bei der Diskussion um DCAT-AP wurde bereits im November 2019 auf den Spielraum aufmerksam gemacht: https://github.com/SEMICeu/DCAT-AP/issues/100 
Leider gab es bislang auf der Ebene von DCAT-AP keine hinreichende Konkretisierung, wie folgendes Issue zeigt: https://github.com/SEMICeu/DCAT-AP/issues/144

**Comment by init-dcat-ap-de** [comment]
Siehe auch: https://github.com/w3c/dxwg/issues/1126

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
