### ISSUE TITLE
Unabhängige Dienste

### ISSUE THREAD

**Issue by HauptJo** [GovDataOfficial/DCAT-AP.de#54]
Es gibt eine Reihe von Funktionen in W3C DCAT2 auf Dienstebene, die in DCAT-AP 2.0.0 nicht übernommen wurden. In der folgenden Aufzählung sind die Eigenschaften aufgeführt, die dem schwedischen Profil hinzugefügt wurden. 

Es gilt zu überlegen, ob wir für das deutsche Profil ähnliche Anforderungen umsetzen müssen.

Alle Ergänzungen betreffen Dienste, bei denen versucht wird, einen Benutzerfall zu antizipieren, bei dem Dienste in größerem Umfang unabhängig beschrieben werden.

**dcterms:publisher** - Für unabhängige Dienste, die nicht mit einem Datensatz verknüpft sind, ist es wichtig zu sehen, wer ihr Herausgeber ist.

**dcat:contactPoint** - Unabhängige Dienste müssen in der Lage sein, Kontaktinformationen einzugeben.
	
**dcterms:type** - Die Verwendung wird auf die Architekturstile REST und RPC beschränkt, da es ziemlich einfach und informativ ist, Dienste danach zu kategorisieren.	

**dcterms:conformsTo** - Es ist wichtig, angeben zu können, welcher Spezifikation der Dienst folgt.

**dcat:landingPage** - Dienste können wie Datensätze eine eigene Zielseite haben.
	
**foaf:page** - Ergänzend zu einem Zeitplan (der vorteilhafterweise über dcat: endpointDescription angegeben wird) wird häufig eine Dokumentation benötigt, insbesondere wenn keine formale Spezifikation mehr geschrieben ist.
	
**dcat:theme** - Verwendet werden die gleichen Kategorien wie für Datensätze.
	
**dcat:keyword** - Schlüsselwörter ergänzen Themen auf die gleiche Weise wie Datensätze.

**Comment by GKStGovData** [comment]
@HauptJo Danke für den Beitrag. Wir werden das Thema bei der Weiterentwicklung von DCAT-AP.de zusammen mit #53 diskutieren. Die Klasse dcat:DataService aus dem schwedischen Profil ist hier näher beschrieben: https://docs.dataportal.se/dcat/en/#dcat%3ADataService

**Comment by init-dcat-ap-de** [comment]
Siehe auch: https://github.com/w3c/dxwg/issues/1253

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
Auf Ebene DCAT-AP noch in der Diskussion.
