### ISSUE TITLE
Neues Rollenkonzept 

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#55]
DCAT2 und DCAT-AP 2.0 erweitern die möglichen Rollen von Personen, die in einer möglichen Verbindung mit den Objekten von DCAT stehen. 

**1. dct:creator**
Die einfachste Änderung stellt dabei die **Einführung von dct:creator** für Datasets dar, die wir in DCAT-AP.de bereits vorweggenommen und im Diskurs um DCAT-AP2.0 eingebracht haben. 
Durch die Subklassenbeziehung zwischen Dataset und Catalog kann nun auch ein Catalog einen dct:creator erhalten:

"dcat:Catalog" --> "*" "foaf:Agent" : <<optional>> NEU: dct:creator

DCAT-AP 2.0 verwendet derzeit die Kardinalität  0..1, da es den “primary creator” bezeichnen soll. Es gibt jedoch bereits eine Diskussion dies auf “*“ zu ändern: https://github.com/SEMICeu/DCAT-AP/issues/171
Daher wird empfohlen, die Kardinalität für beide Eigenschaften auf „*“ zu setzen.

**2. dcat:qualifiedRelationship / dcat:Relationship**
![dcatqualifiedRelationship_dcatRelationship](https://user-images.githubusercontent.com/40267626/107968721-ffb55a80-6fae-11eb-9388-ffe22a290ae3.png)

Wichtig ist zu verstehen, dass dcat:Relationship und dct:qualifiedRelation die Beziehung zwischen verschiedenen Ressourcen beschreibt. Dies kann ggf. für die Abbildung von Datenreihen verwendet werden, allerdings gibt es hierzu auf Ebene des W3Cs andere Vorschläge: https://github.com/w3c/dxwg/issues/1272.
Mittels dcat:qualifiedRelation, dcat:Relationship und dcat:hadRole/dcat:Role kann jede erdenkliche Verbindung zwischen zwei Ressourcen abgebildet werden. Explizit wird zudem prov:wasGeneratedBy eingeführt. 
DCAT-AP beschränkt diese Verknüpfungen auf Datasets.
Es wird vorgeschlagen, diese Eigenschaften und Klassen zu übernehmen:

**(A) Neue Klasse: dcat:Relationship**

```
class "dcat:Relationship" <<NEW: optional>> {
}

"dcat:Relationship" --> "1..*" "dcat:Role" : <<mandatory>> NEW: dcat:hadRole
"dcat:Relationship" --> "1..*" "rdfs:Resource" : <<mandatory>> NEW: dct:relation
```

![dctRelationSchaubild](https://user-images.githubusercontent.com/40267626/107969200-bd404d80-6faf-11eb-82ab-5430789ab531.png)

**(B) Neue Klasse: dcat:Role**
```
class "dcat:Role" <<NEW: optional>> {
}
```
https://www.w3.org/TR/vocab-dcat-2/%23Class:Role#Class:Role 

Eine dcat:Role ist die Funktion eines prov/foaf:Agent (bei Verwendung mit prov:qualifiedAttribution) oder einer dcat:Resource (bei Verwendung mit dcat:qualifiedRelation) mit Bezug auf eine Ressource. 
Es handelt sich um eine Subklasse von skos:Concept.

Das W3C empfiehlt die Verwendung von kontrollierten Vokabularen. Die Empfehlung von Vokabularen sollte diskutiert werden.

**(C) Ergänzung in dcat:Dataset**

```
NEU: <<optional>> prov:wasGeneratedBy ~> prov:Activity [*]
"dcat:Dataset" --> "*" "dcat:Relationship" : <<optional>> NEW: dcat:qualifiedRelation

```

**3. prov:qualifiedAttribution/prov:Attribution** 

Über die Eigenschaft prov:qualifiedAttribution und die Klasse prov:Attribution kann eine Vielzahl von Verbindungen zwischen Resourcen (insbesondere dcat:Dataset) und Personen/Organisationen hergestellt werden.
Den Bedarf, mehr Verbindungen darstellen zu können, haben wir bisher mit den eigenen Eigenschaften dcatde:originator, dcatde:maintainer verwendet. Beide Typen finden sich auch im empfohlenen kontrollierten Vokabular https://id.loc.gov/vocabulary/relators.html:

Aus
```
:originator a foaf:Person .
:dataset dcatde:originator :originator 
```
kann werden: 
```
:originator a foaf:Person, prov:Agent .
:dataset prov:qualifiedAttribution [
    dcat:hadRole < http://id.loc.gov/vocabulary/relators/org> ;
    prov:agent :originator
] .
```
Es muss diskutiert werden, wie in Zukunft mit den bestehenden Sonder-Eigenschaften umgegangen wird (z.B. deprecated). Die semantische Gleichheit unserer Werte mit denen der [MARC relators](https://id.loc.gov/vocabulary/relators.html) sollte abgeglichen werden und bei Bedarf ein anderes Vokabular gesucht werden. Alternativ könnte eine eigene Wertelist erstellt werden.

In diesem Zusammenhang sollte die Klasse prov:Attribution zum UML-Diagramm hinzugefügt werden und in der Spezifikation beschrieben werden, auch wenn DCAT-AP darauf verzichtet hat. Sie sollte mittels „prov:qualifiedAttribution“ durch dcat:Dataset, dcat:Catalog und dcat:DataService eingebunden werden können.

**Comment by init-dcat-ap-de** [comment]
dcatde:originator | [marc:originator](https://id.loc.gov/vocabulary/relators/org.html) | [marc:copyright_holder](https://id.loc.gov/vocabulary/relators/cph.html) | [marc:compiler](https://id.loc.gov/vocabulary/relators/com.html)
----|----|----|----
(468 mal verwendet) <br>Diese Eigenschaft verweist auf die Stellen oder Personen, die Urheberrechte an den Daten besitzen | A person or organization performing the work, i.e., the name of a person or organization associated with the intellectual content of the work. This category does not include the publisher or personal affiliation, or sponsor except where it is also the corporate author | A person or organization to whom copy and legal rights have been granted or transferred for the intellectual content of a work. The copyright holder, although not necessarily the creator of the work, usually has the exclusive right to benefit financially from the sale and use of the work to which the associated copyright protection applies | A person, family, or organization responsible for creating a new work (e.g., a bibliography, a directory) through the act of compilation, e.g., selecting, arranging, aggregating, and editing data, information, etc

dcatde:maintainer | [marc:data_manager](https://id.loc.gov/vocabulary/relators/dtm.html) | [marc:editor](https://id.loc.gov/vocabulary/relators/edt.html)
----|----|----
(14665 mal verwendet) <br>Diese Eigenschaft verweist auf Stellen oder Personen, die Verantwortung und Rechenschaftspflicht für die Daten und ihre angemessene Pflege übernimmt. | A person or organization responsible for managing databases or other data sources | A person, family, or organization contributing to a resource by revising or elucidating the content, e.g., adding an introduction, notes, or other critical matter. An editor may also prepare a resource for production, publication, or distribution. For major revisions, adaptations, etc., that substantially change the nature and content of the original work, resulting in a new work, see author


Ein 100%iger Match besteht unserer Meinung nach nicht zwischen den Eigenschaften von DCAT-AP.de und MARC.

**Comment by init-dcat-ap-de** [comment]
Die Beschränkung auf das Dataset war ein Irrtum: https://github.com/SEMICeu/DCAT-AP/issues/183

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
