### ISSUE TITLE
Änderungen der Eigenschaften von dct:temporal und dct:PeriodOfTime

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#57]
Die Verbindlichkeit der dcat:Dataset-Eigenschaft dct:temporal wurde von optional auf empfohlen erhöht.

Die Klasse dct:PeriodOfTime verzichtet künftig auf schema:startDate und schema:endDate zu Gunsten von dcat:startDate und dcat:endDate. Die Range ist rdfs:Literal typed als xsd:date oder xsd:dateTime, die Verbindlichkeit „empfohlen“.

Außerdem wird als optionale Eigenschaften time:hasBeginning und time:hasEnd eingeführt. Deren Range ist „time:Instant“, damit kommen diese Eigenschaften in Frage, falls z.B. ein vom Standard abweichender Kalender verwendet werden soll.

**die Klasse dct:PeriodOfTime und dct:temporal**
```
class "dct:PeriodOfTime" <<GEÄNDERT: recommended>> {
    GELÖSCHT: <<optional>> schema:startDate ~> rdfs:Literal [0..1]
    GELÖSCHT: <<optional>> schema:endDate ~> rdfs:Literal [0..1]

    NEU: <<recommended>> dcat:startDate ~> rdfs:Literal [0..1]
    NEU: <<recommended>> dcat:endDate ~> rdfs:Literal [0..1]

    NEU: <<optional>> time:hasBeginning ~> time:Instant [0..1]
    NEU: <<optional>> time:hasEnd ~> time:Instant [0..1]
}

"dcat:Dataset" --> "*" "dct:PeriodOfTime" : <<recommended>> dct:temporal
```
![PeriodofTimeDiagramm](https://user-images.githubusercontent.com/40267626/107981234-f7b2e600-6fc1-11eb-93f3-4f5f68a70066.png)

Eine Lösung zur Umsetzung in DCAT-AP.de wäre die aktuell gültigen Eigenschaften schema:startDate und schema:endDate auf „deprecated“ zu setzen und durch die äquivalenten dcat-Eigenschaften zu ersetzen.

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
