### ISSUE TITLE
Neue Eigenschaften zur Beschreibung der zeitlichen und räumlichen Abdeckung

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#58]
Bei DCAT-AP 2.0 wurden neue Eigenschaften zur Beschreibung der zeitlichen und räumlichen Abdeckung eingeführt und die Kardinalität von bestehenden Eigenschaften geändert. 

**1.**
Mit locn:geometry (optional) dcat:bbox (empfohlen) und dcat:centroid (empfohlen) neue Eigenschaften zur Abbildung der geographischen Abdeckung eingeführt. 

Bei der Diskussion zur Einführung dieser Eigenschaften sollte das Thema räumliche Abdeckung in seiner Gesamtheit und insbesondere unter Einbeziehung der Konventionen 4-11 des [Konventionenhandbuchs](https://www.dcat-ap.de/def/dcatde/1.1/implRules.pdf) und #51 betrachtet werden. 

**2.**
Mit dcat:temporalResolution und dcat:spatialResolutionInMeters gibt es neue Eigenschaften zur Abbildung der zeitlichen, bzw. räumlichen Auflösung. 
Bei DCAT-AP.de 1.1 lässt sich die zeitliche Auflösung über dcat:granularity abbilden. Unter Berücksichtigung der aktuellen Verwendung von dcat:granularity sollte diskutiert werden, ob dcat:granularity auf deprecated gesetzt werden sollte und dcat:temporalResolution eingeführt werden sollte.   

**3.** 
Die Kardinalität von dct:spatial wurde für die Klassen dcat:Catalog und dcat:Dataset von optional auf empfohlen hochgestuft. Da für Datennutzende häufig die Angaben zur räumlichen Abdeckung wichtig sind, sollte dies auch bei DCAT-AP.de übernommen werden.

**Comment by init-dcat-ap-de** [comment]
Bezüglich der Kardinalität von bbox, centroid und geometry sollte auch folgendes Issue berücksichtigt bzw. beobachtet werden: https://github.com/SEMICeu/DCAT-AP/issues/175

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
