### ISSUE TITLE
Weitere Änderungen aus DCAT2 bzw. DCAT-AP 2.0 

### ISSUE THREAD

**Issue by GKStGovData** [GovDataOfficial/DCAT-AP.de#59]
Mit den Issues #52 #53 #54 #55 #56 #57 und #58 wurden bereits größere Änderungsbedarfe  die sich aus DCAT2 bzw. DCAT-AP 2.0 ergeben ausführlich dargelegt. 

In diesem Ticket werden zusätzliche Änderungsbedarfe aufgeführt, die sich aus DCAT2 und DCAT-AP 2.0 ergeben. Aufgrund der Vielzahl der Änderungen erscheint die Abbildung aller CRs in extra Issues als nicht zweckmäßig. Grundsätzlich sind alle Änderungen seit der DCAT-AP V 1.1 relevant. Den [Changelog](https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.0.1/DCAT_AP_2.0.1.pdf) finden Sie am Ende der Spezifikation der DCAT-AP 2.0.1. 

Im Folgenden werden noch einmal Änderungen aus DCAT-AP 2.0 genannt, die bei der Weiterentwicklung von DCAT-AP.de berücksichtigt werden, aber aufgrund der zu erwartenden Auswirkungen hier nicht detaillierter beschrieben werden: 

- Änderungen bei dct:Language (siehe auch: https://github.com/SEMICeu/DCAT-AP/issues/88)
- die neue Eigenschaft odrl:hasPolicy (siehe auch: https://github.com/SEMICeu/DCAT-AP/issues/77)
- die neue Eigenschaft dct:isRefrencedBy (siehe auch: https://github.com/SEMICeu/DCAT-AP/issues/75) 
- neue Eigenschaften von dcat:Catalog (siehe auch: https://github.com/SEMICeu/DCAT-AP/issues/72) 
- die neue Eigenschaft dcatap:availability (siehe auch: https://github.com/SEMICeu/DCAT-AP/issues/40) 
- die Streichung von adms:status bei Catalog Record (siehe auch: https://github.com/SEMICeu/DCAT-AP/issues/45)
-  die Änderung der Eigenschaft adms:verionNotes (siehe auch: https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/discussion/co4-replace-admsversion-owlversioninfo)

**Comment by init-dcat-ap-de** [comment]
Zur dcatap:availability, siehe auch: https://github.com/SEMICeu/DCAT-AP/issues/178

**Comment by init-dcat-ap-de** [comment]
Mit dem Release von [DCAT-AP.de 2.0](https://www.dcat-ap.de/def/dcatde/2.0/spec/) umgesetzt.
