### ISSUE TITLE
[V 1.1] dct:language - Sprachangabe bei mehrsprachigen Angaben

### ISSUE THREAD

**Issue by schiersner** [GovDataOfficial/DCAT-AP.de#6]
**Bezug:** DCAT-AP.de Konventionenhandbuch 1.0.1, 
"1.1.3 Sprachangabe bei mehrsprachigen Angaben, Konv 3"

**Bedarf:** Im Land Brandenburg hat die Bewahrung und Förderung der Sprache der Sorben und Wenden Verfassungsrang [1]. Für Sorbisch/Wendisch gibt es jedoch keine Alpha-2 Notation mit zwei Buchstaben, sondern nur eine Alpha-3 Notation ("dsb" bzw. "hsb") gemäß ISO 639.2 wie sie von der Library of Congress gepflegt wird [2]. Die im Konventionenhandbuch geforderte Verwendung der Sprachcodes gemäß BCP47 [3] schließt Alpha-3 Notation ausdrücklich mit ein. Einschränkung: RFC 3066 Abschnit 2.3 schreibt vor, dass auf Alpha-3 verzichtet werden soll, wenn es zur gewählten Sprache eine Alpha-2 Kodierung gibt.

**Lösungsvorschlag:** Ergänzung der Konvention 3 um den Satz: 
"_Bei Sprachen für die es keine Alpha-2 Notierung gibt, ist eine Alpha-3 Notierung zulässig._"

[1] Verfassung des Landes Brandenburg, Artikel 25, Abs. 3 und 4 https://bravors.brandenburg.de/de/gesetze-212792#25
[2] https://www.loc.gov/standards/iso639-2/php/code_list.php
[3] https://tools.ietf.org/html/bcp47

**Comment by GKStGovData** [comment]
Vielen Dank für den Beitrag. Die angeregte Änderung wurde als CR2018/53 behandelt und in der DCAT-AP.de Version 1.0.2 umgesetzt. (Quelle: [https://github.com/GovDataOfficial/DCAT-AP.de/blob/master/CR-Dokumentation_1.0.2.xlsx]).
