### ISSUE TITLE
Sammlung

### ISSUE THREAD

**Issue by jze** [GovDataOfficial/DCAT-AP.de#61]
Das Thema ist ähnlich zu #40, aber möglicherweise im Detail etwas anders.

Gesucht wird eine Lösung zum Erstellen von _Sammlungen_, eine kuratierte Zusammenstellung von Datensätzen, die man benötigt, um einen Sachverhalt gut zu verstehen. Bei Daten aus dem Kulturbereich ist mir das oft begegnet, da gibt es in der Regel solche Sammlungen bereits. Aber auch in anderen Domänen sind solche Übersichten sinnvoll, z.B. zur Wasserrahmenrichtlinie in Schleswig-Holstein, wo mindestens diese Datensätze https://opendata.schleswig-holstein.de/tag/WRRL berücksicht und erklärt werden sollten. Auch ein Thema wie "Luftqualität" könnte eine Sammlung sein.

Vielleicht benötigt es eine ganz neue und von dcat:Dataset unabhängige Struktur. 

Oder ist das gar kein DCAT-AP.de Thema und die Sammlungen sollten nur innerhalb der jeweiligen Portale umgesetzt werden?

**Comment by init-dcat-ap-de** [comment]
Für Sammlungen könnte man ggf. den Katalog benutzen:

> A curated collection of metadata about resources (e.g., datasets and data services in the context of a data catalog)
https://www.w3.org/TR/vocab-dcat-2/#Class:Catalog
