### ISSUE TITLE
[V 1.1] dcat:mediaType auf URI umstellen

### ISSUE THREAD

**Issue by schiersner** [GovDataOfficial/DCAT-AP.de#7]
**Bezug:** DCAT-AP.de Konventionenhandbuch 1.0.1, 
"1.2.1  dcat:mediaType und dct:format, Konv 31"

**Bedarf:** Das Semantische Web baut auf Triples und URIs auf. Soll das Semantische Web Wirklichkeit werden, ist wo immer möglich, eine URI als Referenz zu nutzen. Da DCAT-AP.de ausdrücklich auf die IANA Bezug [1] nimmt und diese eindeutige URIs definiert, sollten diese bevorzugt werden.

**Lösungsvorschlag:** Im Beispiel unter Konvention 31 sollte `"text/csv"` ersetzt werden durch `"https://www.iana.org/assignments/media-types/text/csv"`.

[1] IANA Media Types https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by akuckartz** [comment]
See also: https://github.com/SEMICeu/DCAT-AP/issues/26

**Comment by larsgsvensson** [comment]
@akuckartz scripsit:
> In case this is not obvious: Literals are not legal values for dcat:mediaType.

Then perhaps you could change the example in Konvention 31 to `<https://www.iana.org/assignments/media-types/text/csv>`, thus making it a URI.

**Comment by GKStGovData** [comment]
Vielen Dank für den Beitrag. Die angeregte Änderung wurde als CR2018/54 behandelt und in der DCAT-AP.de Version 1.0.2 umgesetzt. (Quelle:  [https://github.com/GovDataOfficial/DCAT-AP.de/blob/master/CR-Dokumentation_1.0.2.xlsx]).
