### ISSUE TITLE
Fehlende Lizenz im Repository

### ISSUE THREAD

**Issue by HannesWuensche** [GovDataOfficial/DCAT-AP.de#71]
Liebes GovData Team,

wir wollen grad eure Readme unserer eigenen Nutzen, da fällt uns auf, dass ihr keine Lizenz für euer Repo habt. 
Ist das so beabsichtigt? 

Liebe Grüße
@Hanneswuensche

**Comment by GKStGovData** [comment]
Hallo @HannesWuensche,

das ist nicht so beabsichtigt. Wir können (und sollten) dem Repo eine Lizenz mitgeben. Der Standard selbst ist unter CC-BY lizensiert. Unser Vorschlag wäre, diese Lizenz auch dem Repo zu geben.

Liebe Grüße,
Thomas

**Comment by GKStGovData** [comment]
Danke @HannesWuensche für den PR und das Issue
