### ISSUE TITLE
Teilnahme am dcatAp.de spec-Prozess

### ISSUE THREAD

**Issue by stbischof** [GovDataOfficial/DCAT-AP.de#75]
@GKStGovData welche Möglichkeiten gibt es am dcatAp.de Spec-Prozess teilzunehmen?

An wen kann man sich wenden?

**Comment by jze** [comment]
Einfach hier Issues erstellen. Mit denen beschäftigt sich dann die Unterarbeitsgruppe DCAT-AP.de der GovData-Fachgruppe.

**Comment by akuckartz** [comment]
Ist die Mitgliedschaft in der Unterarbeitsgruppe öffentlich?

**Comment by GKStGovData** [comment]
Die GovData-Fachgruppe ist mit Vertreter:innen der Bundesländer und dem Bund besetzt. Die Unterarbeitsgruppe besteht aus Mitglieder:innen dieser Fachgruppe.

Die praktische Mitarbeit geht am einfachsten über Issues hier auf GitHub (wie @jze es bereits beschrieben hat)
