### ISSUE TITLE
Remove MD-1 Algorithm

### ISSUE THREAD

**Issue by init-dcat-ap-de** [GovDataOfficial/DCAT-AP.de#8]
The MD-1 algorithm from our [list of algorithms](https://www.dcat-ap.de/def/hashAlgorithms/) probably does not exist.

So it should be safe to remove it.

**Comment by akuckartz** [comment]
How was this resolved?

**Comment by init-dcat-ap-de** [comment]
It was resolved by removing MD-1 from the list and from the documents.
