### ISSUE TITLE
W3ID is not affiliated with W3C

### ISSUE THREAD

**Issue by hoehrmann** [GovDataOfficial/DCAT-AP.de#81]
https://www.dcat-ap.de/def/dcatde/2.0/spec/ contains »W3ID (W3C Permanent Identifiers for the Web: https://w3id.org/)« but the web site says at the bottom »the "World Wide Web Consortium" (W3C) is not involved in the support or management of this website in any way.«

**Comment by init-dcat-ap-de** [comment]
Thank you for the feedback, we changed the description in 3.0: https://www.dcat-ap.de/def/dcatde/3.0/spec/#datensatz-andere-id
